# Generated by Django 5.2.4 on 2025-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phoneNumber",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("linkedId", models.IntegerField(blank=True, default=None)),
                (
                    "linkPrecedence",
                    models.CharField(choices=[("PM", "primary"), ("SC", "secondary")]),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateField(auto_now_add=True)),
                ("deletedAt", models.DateField(blank=True, default=None)),
            ],
        ),
    ]
