# Generated by Django 5.2.4 on 2025-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="deletedAt",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="linkedId",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phoneNumber",
            field=models.CharField(
                blank=True, default=None, max_length=10, null=True, unique=True
            ),
        ),
    ]
