# Generated by Django 5.2.4 on 2025-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="linkedId",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
