# Generated by Django 5.2.4 on 2025-07-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_contacts_linkedid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="deletedAt",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
