# Generated by Django 5.2.4 on 2025-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_alter_contacts_deletedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
