# Generated by Django 5.2.4 on 2025-07-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0004_alter_contacts_email_alter_contacts_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phoneNumber",
            field=models.CharField(
                blank=True, default=None, max_length=10, null=True, unique=True
            ),
        ),
    ]
